# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Destroyer
version:      0.1
version_from: lib/Object/Destroyer.pm
installdirs:  site
requires:
    Carp:                          0
    File::Spec:                    0.83
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
