abstract: Make objects with circular references DESTROY normally
author: Adam Kennedy <adamk@cpan.org> and Igor Gariev <gariev@hotmail.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Object-Destroyer
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  perl: 5.005
version: 2.00
